rm(list = ls())

############## 1. Data Loading & Initial Inspection ##############

mower.df <- read.csv("./basic/data/RidingMowers.csv", na.strings = "")

dim(mower.df)
head(mower.df, n = 10)

str(mower.df)
summary(mower.df)

##################### 2. Data Preprocessing #####################

mower.df$Ownership <- factor(mower.df$Ownership)
str(mower.df)

rownames(mower.df)
dim(mower.df)[1]

###################### 3. Data Partitioning ######################

# ====================== 3-1. Train & Valid ======================

set.seed(20)
train.index <- sample(rownames(mower.df), 0.6 * dim(mower.df)[1])
train.index

class(train.index)
length(train.index)

valid.index <- setdiff(rownames(mower.df), train.index) # 차집합
valid.index

length(valid.index)

train.df <- mower.df[train.index, ]
valid.df <- mower.df[valid.index, ]

dim(train.df)
dim(valid.df)

head(train.df)
rownames(train.df) <- c(1:14) # 번호 다시 매기기

rownames(train.df)
head(train.df)

# ========================== 3-2. New ==========================

new.df <- data.frame(Income = c(60, 70, 80), Lot_Size = c(20, 21, 17))
new.df

# ========================== 3-3. Plot ==========================

# pch: plotting character, 1 = O, 3 = +
plot(Lot_Size ~ Income, data = train.df, pch = ifelse(train.df$Ownership == "Owner", 1, 3))

text(train.df$Income, train.df$Lot_Size, rownames(train.df), pos = 4)

text(60, 20, "X")
text(70, 21, "Y")
text(80, 17, "Z")

legend("topright", c("owner", "non-owner", "newhousehold"), pch = c(1, 3, 4))

####################### 4. Normalize Data #######################

# =================== 4-1. Define Normalizer ===================

library(caret)

# normalizer by mean & deviation
preProc <- preProcess(train.df[, 1:2], method = c("center", "scale"))

train.norm.df <- train.df
train.norm.df
dim(train.norm.df)

# ================= 4-2. Normalize by Normalizer =================

# request normalize to normalizer
predict(preProc, train.df[, 1:2])

train.norm.df[, 1:2] <- predict(preProc, train.df[, 1:2])
head(train.norm.df)

# alternatively, normalize then combine (cf. copy and normalize)
# train.norm.df1 <- cbind(predict(preProc, train.df[, 1:2]), Ownership = train.df$Ownership)
# head(train.norm.df1)
# rm(train.norm.df1)

valid.norm.df <- valid.df
# why use normalizer which is generated by train.df? => standard must be train data
valid.norm.df[, 1:2] <- predict(preProc, valid.df[, 1:2])
head(valid.norm.df)

new.df
# also new.df normalizing => standard must be train data
new.norm.df <- predict(preProc, new.df)
head(new.norm.df)

###################### 5. kNN Classification ######################

# ====================== 5-1. Classification ======================

# install KNN
# install.packages("FNN")
# library(FNN)

# FNN::knn => run func without installing & loading
# cl => classification (ans at 3rd col)
nn <- FNN::knn(train = train.norm.df[, 1:2], test = new.norm.df, cl = train.norm.df[, 3], k = 3)
nn

# nn1 <- class::knn(train = train.norm.df[, 1:2], test = new.norm.df, cl = train.norm.df[, 3], k = 3)
# nn1

# nbrs = neighbors
nbrs <- attr(nn, "nn.index")
nbrs

colnames(nbrs) <- c("1st NN", "2nd NN", "3rd NN")
rownames(nbrs) <- c("New 1", "New 2", "New 3")
nbrs
new.df

# ===================== 5-2. Find Optimal K =====================

# find optimal k value
accuracy.df <- data.frame(k = seq(1, 14, 1), accuracy = rep(0, 14))
accuracy.df

head(valid.norm.df)

knn.pred <- class::knn(train = train.norm.df[, 1:2], test = valid.norm.df[, 1:2], cl = train.norm.df[, 3], k = 3)
knn.pred

for (i in 1:14) {
  knn.pred <- class::knn(train = train.norm.df[, 1:2], test = valid.norm.df[, 1:2], cl = train.norm.df[, 3], k = i)
  accuracy.df[i, 2] <- confusionMatrix(knn.pred, valid.norm.df[, 3])$overall[1] # overall[1] => overall accuracy
}

accuracy.df

#################### 6. Example - 3 Partitions ####################

# example: partition to 3
set.seed(99)

# replace = TRUE => 복원 추출
spl <- sample(c(1:3), size = nrow(mower.df), replace = TRUE, prob = c(0.6, 0.2, 0.2))
spl

train3 <- mower.df[spl == 1, ]
dim(train3)

valid3 <- mower.df[spl == 2, ]
dim(valid3)

test3 <- mower.df[spl == 3, ]
dim(test3)
